import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.link_one}>
          <Link style={{ textDecoration: 'none',  color: 'white' }} href="/useEffectOne">useEffectOne</Link>
        </div>
       <div className={styles.link_two}>
        <Link style={{ textDecoration: 'none', color: 'aliceBlue'}} href="/useEffectTwo">useEffectTwo</Link>
       </div>
       <div className={styles.link_three}>
        <Link style={{ textDecoration: 'none', color: 'rgb(252, 232, 255)' }} href="/useEffectThree">useEffectThree</Link>
       </div>
       <div className={styles.link_carousel}>
        <Link style={{ textDecoration: 'none', color: 'white' }} href="/carouselPage">carouselPage</Link>
       </div>
       
      </main>
    </>
  )
}
